### ISSUE TITLE
Question on Contribution and authorship

### ISSUE THREAD

**Issue by pythonpanda2** [benjaminbolling/DynaGUI#2]
@benjaminbolling

Seems like there are two main contributors to this repo. Why is the other contributor [@danielskatz] not listed in the authourship or in the acknowledgment ?

**Comment by danielskatz** [comment]
My only contribution was some copy-editing fixes in the paper as a JOSS Associate-Editor-in-Chief when this was submitted.  I should not be listed as a contributor to the paper or software.
