### ISSUE TITLE
Where is the Example usage?

### ISSUE THREAD

**Issue by Chilipp** [benjaminbolling/DynaGUI#7]
Hi @benjaminbolling,

as part of the review in https://github.com/openjournals/joss-reviews/issues/1942, I could not find the section about the example usage. 

> **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Could you please point me to the place where to find it?

**Comment by benjaminbolling** [comment]
I have put some example usage in the README file, please let me know if it is sufficient or not.

**Comment by Chilipp** [comment]
Sorry @benjaminbolling, but I can't see how this is an example usage, but probably there is a misunderstanding. The Example Usage should guide the user through an example, something like a _Getting started_ section. What you wrote down here is about how _you_ used and developed the package. It should however be an **example** about how the _user_ can use, and get started with your software.

**Comment by benjaminbolling** [comment]
Aha, I see. My mistake, I will update it during the weekend and turn it into a more proper _getting started_. Thank you @Chilipp

**Comment by benjaminbolling** [comment]
@Chilipp Sorry for not responding to this more urgently, I had a lot of things to attend to which kept on pushing this task. Again, sorry for this. I have updated the Readme file such that there is a section User Guide which points the reader towards the UserGuide.pdf file. Is this sufficient or would you prefer to have (parts of) that text in the Readme file directly?

**Comment by Chilipp** [comment]
Hi @benjaminbolling, apologies for the delay! I am quite busy at the moment, too :sweat_smile:. So what I understand of an _Example usage_ is a section like this: https://psyplot.readthedocs.io/projects/psy-view/en/latest/getting-started.html. It's a guide with some initial data or so that the user can run through to get an initial impression of the software after having it installed. This is also, what the JOSS requirements say:

> Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I could not find something comparable in your user guide. 

Do you have something like this? Or do you think this is impossible to generate for DynaGUI? Or do you think it's not valuable for DynaGUI (in which case we need to ask the editor, how to proceed)?

**Comment by benjaminbolling** [comment]
@Chilipp : I have begun writing a Getting Started section and will soon continue (in a few hours). If you see this comment and you have time to do a quick check, let me know if that is what you meant. 🙂

**Comment by benjaminbolling** [comment]
Dear @Chilipp, I have now completed a getting started section. Please let me know if this is what you had in mind.

**Comment by Chilipp** [comment]
LGTM, thanks @benjaminbolling!
