### ISSUE TITLE
Create community guidelines

### ISSUE THREAD

**Issue by Chilipp** [benjaminbolling/DynaGUI#9]
> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

As a requirement for https://github.com/openjournals/joss-reviews/issues/1942, please add a CONTRIBUTING file, or something comparable

see https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors for some help

**Comment by benjaminbolling** [comment]
I have created the CONTRIBUTING.md file, please check if you consider it as sufficient or not.

**Comment by Chilipp** [comment]
hi @benjaminbolling. If it's sufficient for you, it's sufficient for me. Thanks! JOSS does not say anything about the quality or necessary contents of this Guide.

One comment, though: People raising issues in your Github repository usually do not have the rights to set _labels_ (e.g. _bug_ or _enhancement_). This is something the code maintainer has to do.
